{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fc177ada",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b61eaa91",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\ext\\extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 2861, in get_updates\n",
      "    self._post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 356, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"C:\\Users\\Dev Bhavsar\\anaconda3\\lib\\site-packages\\telegram\\utils\\request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    }
   ],
   "source": [
    "import telegram.ext\n",
    "\n",
    "def start(update, context):\n",
    "    user_name = update.message.from_user.first_name\n",
    "    update.message.reply_text(f\"Hello, {user_name}! Welcome to  channel.\")\n",
    "\n",
    "def help(update, context):\n",
    "    update.message.reply_text(\"\"\"\n",
    "    The following commands are available:\n",
    "    \n",
    "    /start -> Welcome to the channel\n",
    "    /help -> This message\n",
    "    /content -> I create this code for my individual project\n",
    "    /Python  -> Our sir Keval Patel teaches us Python\n",
    "    /SQL -> SQL is great\n",
    "    /Java -> The first video from Java Playlist\n",
    "    /Skillup -> Python, FSD , daa \n",
    "    /contact -> My contact number is 9727481889\n",
    "    /collage -> DAA SUB IS USEFUL \n",
    "    \n",
    "    \"\"\")\n",
    "\n",
    "def content(update, context):\n",
    "    update.message.reply_text(\"We have various playlists and articles available!\")\n",
    "\n",
    "def Python(update, context):\n",
    "    update.message.reply_text(\"Our sir Keval Patel teaches us Python\")\n",
    "\n",
    "def SQL(update, context):\n",
    "    update.message.reply_text(\"SQL is great\")\n",
    "\n",
    "def Java(update, context):\n",
    "    update.message.reply_text(\"The first video from Java Playlist\")\n",
    "\n",
    "def Skillup(update, context):\n",
    "    update.message.reply_text(\"Python, FSD , DAA\")\n",
    "\n",
    "def contact(update, context):\n",
    "    update.message.reply_text(\"My contact number is 9727481889\")\n",
    "    \n",
    "def collage(update, context):\n",
    "    update.message.reply_text(\"this is collage functions\")\n",
    "\n",
    "def handle_message(update, context):\n",
    "    update.message.reply_text(f\"You said {update.message.text}, use the commands using /\")\n",
    "    \n",
    "\n",
    "\n",
    "Token = \"6846323171:AAE4Pjobw5It6z5mAX4ApH92kRWvpSyUagI\"\n",
    "updater = telegram.ext.Updater(Token, use_context=True)\n",
    "disp = updater.dispatcher\n",
    "\n",
    "disp.add_handler(telegram.ext.CommandHandler('start', start))\n",
    "disp.add_handler(telegram.ext.CommandHandler('help', help))\n",
    "disp.add_handler(telegram.ext.CommandHandler('content', content))\n",
    "disp.add_handler(telegram.ext.CommandHandler('Python', Python))\n",
    "disp.add_handler(telegram.ext.CommandHandler('SQL', SQL))\n",
    "disp.add_handler(telegram.ext.CommandHandler('Java', Java))\n",
    "disp.add_handler(telegram.ext.CommandHandler('Skillup', Skillup))\n",
    "disp.add_handler(telegram.ext.CommandHandler('contact', contact))\n",
    "disp.add_handler(telegram.ext.CommandHandler('collage',collage))\n",
    "disp.add_handler(telegram.ext.MessageHandler(telegram.ext.Filters.text, handle_message))\n",
    "\n",
    "updater.start_polling()\n",
    "updater.idle()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "22d9ff25",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
